version: '3.1'

services:
  mongo:
      image: mongo:3.4.3
      ports:
        - 27017:27017
  app:
    image: kevin:latest
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: 'local'
